[build]
  command = "npm run build"
  publish = "deploy"

# Editor SPA deep link handling
[[redirects]]
  from = "/editor/*"
  to = "/editor/index.html"
  status = 200

# Teacher/Student sections (routes land on their own HTML entrypoints)
[[redirects]]
  from = "/teacher/*"
  to = "/Teacher/homepage.html"
  status = 200

[[redirects]]
  from = "/student/*"
  to = "/Student/homepage.html"
  status = 200

# Optional: catch-all SPA fallback for root app
# [[redirects]]
#   from = "/*"
#   to = "/index.html"
#   status = 200

# Security & caching headers (baseline)
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "SAMEORIGIN"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
    Cache-Control = "public, max-age=600"

[[headers]]
  for = "/robots.txt"
  [headers.values]
    Cache-Control = "no-cache"

# Env vars (if needed later for Firebase / APIs)
# [build.environment]
#   VITE_FIREBASE_API_KEY = "..."
