[build]
  command = "npm run build"
  publish = "deploy"

# Editor SPA deep link handling
[[redirects]]
  from = "/editor/*"
  to = "/editor/index.html"
  status = 200

# Generic fallback for other routes that should land on root index (optional)
[[redirects]]
  from = "/teacher/*"
  to = "/Teacher/homepage.html"
  status = 200

[[redirects]]
  from = "/student/*"
  to = "/Student/homepage.html"
  status = 200

# Catch-all: if you prefer SPA fallback to root uncomment below
# [[redirects]]
#   from = "/*"
#   to = "/index.html"
#   status = 200

# Security & caching headers (basic baseline)
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "SAMEORIGIN"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
    Cache-Control = "public, max-age=600"

[[headers]]
  for = "/robots.txt"
  [headers.values]
    Cache-Control = "no-cache"

# You can add environment variables here later if moving Firebase config:
# [build.environment]
#   VITE_FIREBASE_API_KEY = "..."
